USE [TNTL_PUR]
GO

/****** Object:  View [dbo].[VW_STG_VENDOR_RESPONSE_TARGET]    Script Date: 18/2/2568 10:08:03 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE VIEW [dbo].[VW_STG_VENDOR_RESPONSE_TARGET] AS 

SELECT *
FROM
(
	SELECT
	SharePoint_List,
	Item_ID,Title,
	[YEAR],
	[GROUP],
	CATEGORY,
	SUB_CATEGORY,
	VENDOR_CODE,
	VENDOR_NAME

	FROM  
	(
		SELECT SHAREPOINT_LIST,ITEM_ID,Title,QUESTION_NAME,RESPONSE FROM STG_VENDOR_RESPONSE_TARGET
		WHERE QUESTION_NAME IN ('YEAR','GROUP','CATEGORY','SUB_CATEGORY','VENDOR_CODE','VENDOR_NAME')
	) AS F
	PIVOT  
	(  
	MIN(RESPONSE) FOR QUESTION_NAME IN ([YEAR],[GROUP],[CATEGORY],[SUB_CATEGORY],[VENDOR_CODE],[VENDOR_NAME])
	) AS P
) A 


GO


