CREATE TABLE FACT_MS_FORM_GROUPING_V2
(
	JoinKey						nvarchar(1100),
	UniqueID					nvarchar(100),
	FormYear					nvarchar(100),
	Function_Name				nvarchar(13),
	Function_SubType			nvarchar(100),
	Scoring_Group				nvarchar(100),
	RoundYear					nvarchar(100),
	SharePoint_List				nvarchar(100),
	SubmissionTime				nvarchar(100),
	ResponderEmail				nvarchar(100),
	Plant						nvarchar(100),
	Pur_Grp						nvarchar(100),
	Level1						nvarchar(500),
	Level2						nvarchar(100),
	Level3						nvarchar(100),
	Vendor_Name					nvarchar(100),
	Product						nvarchar(100),
	Comment						nvarchar(1000),
	Above1MB					nvarchar(100),
	Group_Question				nvarchar(100),
	Question_Number				nvarchar(3),
	Question_Name				nvarchar(300),
	Response_Value				decimal(25,4),
	Weight_Source				decimal(9,4),
	Max_Response_Value			decimal(25,4),
	Raw_Score					decimal(20,4),
	Score						decimal(9,4),
	Total_Question_In_Group		int,
	Weight_Calc					decimal(9,4),
	Weight_Total_Line			decimal(9,4)
)