USE [TNTL_PUR_DEV]
GO

/****** Object:  View [dbo].[VW_FORM_01_UNION]    Script Date: 19/5/2568 16:57:41 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO












CREATE VIEW [dbo].[VW_FORM_01_UNION] AS 

SELECT * FROM VW_STG_MS_FORM_COM
UNION ALL 
SELECT * FROM VW_STG_MS_FORM_IT
UNION ALL 
SELECT * FROM VW_STG_MS_FORM_LOGISTIC
UNION ALL 
SELECT * FROM VW_STG_MS_FORM_RENTAL
UNION ALL 
SELECT * FROM VW_STG_MS_FORM_MFG
UNION ALL 
SELECT * FROM VW_STG_MS_FORM_OUTSOURCE
UNION ALL 
SELECT * FROM VW_STG_MS_FORM_UNIFORM
UNION ALL 
SELECT * FROM VW_STG_MS_FORM_WASTE
UNION ALL 
SELECT * FROM VW_STG_MS_FORM_EXTERNAL
UNION ALL 
SELECT * FROM VW_STG_MS_FORM_INTERNAL
UNION ALL 
SELECT * FROM VW_STG_MS_FORM_RM
UNION ALL 
SELECT * FROM VW_STG_MS_FORM_AGILE
UNION ALL 
SELECT * FROM VW_STG_MS_FORM_PROPERTY
UNION ALL 
SELECT * FROM VW_STG_MS_FORM_ENERGY_CHEMICAL
GO


