USE [TNTL_PUR_DEV]
GO

/****** Object:  StoredProcedure [dbo].[SP_PROC_MS_FORM]    Script Date: 18/4/2568 17:02:16 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[SP_PROC_MS_FORM] AS 
BEGIN

--TRUNCATE TABLE FACT_MS_FORM_SCORE;
--INSERT INTO FACT_MS_FORM_SCORE
--SELECT * FROM VW_FORM_06_SCORE
--WHERE RAW_SCORE IS NOT NULL;

--TRUNCATE TABLE FACT_MS_FORM_GROUPING
--INSERT INTO FACT_MS_FORM_GROUPING
--SELECT * FROM VW_FACT_MS_FORM_GROUPING


--DELETE FROM FACT_MS_FORM_SCORE_V2 WHERE FormYear = YEAR(GETDATE());
--INSERT INTO FACT_MS_FORM_SCORE_V2
--SELECT * FROM VW_FORM_06_SCORE_v2
--WHERE	FormYear = YEAR(GETDATE())
--		AND RAW_SCORE IS NOT NULL;

--DELETE FROM FACT_MS_FORM_GROUPING_V2 WHERE FormYear = YEAR(GETDATE())
--INSERT INTO FACT_MS_FORM_GROUPING_V2
--SELECT * FROM VW_FACT_MS_FORM_GROUPING_V2
--WHERE	FormYear = YEAR(GETDATE())


TRUNCATE TABLE FACT_MS_FORM_SCORE_V2;
INSERT INTO FACT_MS_FORM_SCORE_V2
SELECT * FROM VW_FORM_06_SCORE_v2
WHERE RAW_SCORE IS NOT NULL;

TRUNCATE TABLE FACT_MS_FORM_GROUPING_V2
INSERT INTO FACT_MS_FORM_GROUPING_V2
SELECT * FROM VW_FACT_MS_FORM_GROUPING_V2

END
GO


