USE [TNTL_PUR]
GO

/****** Object:  View [dbo].[VW_STG_DIM_VENDOR_WASTE]    Script Date: 18/2/2568 9:22:11 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO







CREATE VIEW [dbo].[VW_STG_DIM_VENDOR_WASTE] AS 

SELECT *
FROM
(
	SELECT
	SharePoint_List,
	Item_ID,Title,
	DATEADD("hour",7,TRY_CAST([UPDATE_DATE] AS DATETIME2(0))) AS UPDATE_DATE,
	COALESCE(VENDOR_CODE,'') AS Vendor_Code,
	COALESCE(VENDOR_NAME,'') AS Vendor_Name

	FROM  
	(
		SELECT SHAREPOINT_LIST,ITEM_ID,Title,QUESTION_NAME,RESPONSE FROM STG_DIM_VENDOR_WASTE
		WHERE QUESTION_NAME IN ('VENDOR_CODE','VENDOR_NAME','UPDATE_DATE')
	) AS F
	PIVOT  
	(  
	MIN(RESPONSE) FOR QUESTION_NAME IN ([VENDOR_CODE],[VENDOR_NAME],[UPDATE_DATE])
	) AS P
) A 

WHERE VENDOR_NAME <> 'À®°.¥«ßæ√√’‰´‡§‘≈'

GO


