USE [TNTL_PUR]
GO

/****** Object:  View [dbo].[VW_FORM_01_UNION]    Script Date: 17/2/2568 16:52:18 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO







CREATE VIEW [dbo].[VW_FORM_01_UNION] AS 

SELECT * FROM VW_STG_MS_FORM_COM
UNION ALL 
SELECT * FROM VW_STG_MS_FORM_IT
UNION ALL 
SELECT * FROM VW_STG_MS_FORM_LOGISTIC
UNION ALL 
SELECT * FROM VW_STG_MS_FORM_RENTAL
UNION ALL 
SELECT * FROM VW_STG_MS_FORM_MFG
UNION ALL 
SELECT * FROM VW_STG_MS_FORM_OUTSOURCE
UNION ALL 
SELECT * FROM VW_STG_MS_FORM_UNIFORM
UNION ALL 
SELECT * FROM VW_STG_MS_FORM_WASTE
UNION ALL 
SELECT * FROM VW_STG_MS_FORM_EXTERNAL
UNION ALL 
SELECT * FROM VW_STG_MS_FORM_INTERNAL
UNION ALL 
SELECT * FROM VW_STG_MS_FORM_RM
GO