USE [TNTL_PUR]
GO

/****** Object:  View [dbo].[VW_FORM_04_WEIGHT]    Script Date: 18/2/2568 9:05:10 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO






CREATE VIEW [dbo].[VW_FORM_04_WEIGHT] AS

SELECT 
COALESCE(F.SHAREPOINT_LIST,'') AS SHAREPOINT_LIST,
Q.YEAR,
Q.FORM_NAME AS FORM_FULL_NAME,
COALESCE(F.FUNCTION_NAME, Q.FUNCTION_NAME) AS FUNCTION_NAME,
Q.LEVEL1 AS FUNCTION_LEVEL1,
Q.LEVEL2 AS FUNCTION_LEVEL2,
LTRIM(RTRIM(COALESCE(F.FUNCTION_SUBTYPE,''))) AS FUNCTION_SUBTYPE,
F.QUESTION_ORDER,
F.QUESTION_NAME AS QUESTION_NAME,
Q.GROUP_QUESTION,
/*
CASE 
	WHEN COALESCE(F.FUNCTION_NAME, Q.FUNCTION_NAME) IN ('RM&PKG') THEN 'WITHIN_GROUP'
	ELSE 'NORMAL'
END AS WEIGHT_TYPE,
*/
CASE 
WHEN COALESCE(F.FUNCTION_NAME, Q.FUNCTION_NAME) IN ('RM&PKG')
-- RM Weighting
THEN 
	CASE 
	WHEN GROUP_QUESTION = 'Service'
	THEN CAST(CAST(Q.WEIGHT AS DECIMAL(9,4)) / 10 AS DECIMAL(9,4)) 
	ELSE CAST(CAST(Q.WEIGHT AS DECIMAL(9,4)) / COUNT(Q.QUESTION) OVER (PARTITION BY Q.FUNCTION_NAME, Q.GROUP_QUESTION,Q.YEAR) AS DECIMAL(9,4))   END
-- Non RM Weighting
ELSE 
CAST( 
CAST(Q.WEIGHT AS DECIMAL(9,6))
/
CAST(SUM(CAST(Q.WEIGHT AS DECIMAL(9,6))) OVER (PARTITION BY F.SHAREPOINT_LIST,  Q.FORM_NAME, Q.YEAR, F.FUNCTION_NAME, F.FUNCTION_SUBTYPE) AS DECIMAL(9,4))
* 100 
AS DECIMAL(9,4))
END
AS WEIGHT_100,
SUM(CAST(Q.WEIGHT AS DECIMAL(9,4))) OVER (PARTITION BY F.SHAREPOINT_LIST, Q.FORM_NAME, Q.YEAR, F.FUNCTION_NAME, F.FUNCTION_SUBTYPE) AS TOTAL_WEIGHT,
CAST(Q.WEIGHT AS DECIMAL(9,4)) AS WEIGHT_SOURCE,
F.MAX_RESPONSE_VALUE,
Q.UPDATE_DATE

FROM 
( 
	SELECT A.* ,
	CASE 
	WHEN FORM_NAME LIKE '%Uniform-DT%' AND [YEAR] = '2021' THEN 'UNIFORM-DT'
	WHEN FORM_NAME LIKE '%Uniform-DT%' AND [YEAR] = '2022' THEN 'UNIFORM' 
	WHEN FORM_NAME LIKE '%Uniform-OF%' THEN 'UNIFORM-OF'
	WHEN FORM_NAME LIKE '%Uniform-WH%' THEN 'UNIFORM-WH'
	WHEN FORM_NAME LIKE '%Uniform-S%' THEN 'UNIFORM-S'
	WHEN FORM_NAME LIKE '%(Uniform) M/F%' THEN 'UNIFORM-M/F'
	WHEN FUNCTION_NAME = 'Procurement' AND LEVEL1 = 'Internal' THEN 'Internal'
	WHEN FUNCTION_NAME = 'Procurement' AND LEVEL1 = 'External' THEN 'External'
	ELSE '' END AS FUNCTION_SUBTYPE
	FROM
	STG_QUESTION A
	

) Q
LEFT JOIN (
 SELECT * FROM VW_FORM_03_DISTINCT_QUESTION 
) F

ON UPPER(F.FUNCTION_NAME) = UPPER(Q.FUNCTION_NAME)
AND COALESCE(F.FUNCTION_SUBTYPE,'') = COALESCE(Q.FUNCTION_SUBTYPE,'')
AND F.Question_Name = Q.QUESTION_DISPLAY
AND F.Formyear = Q.YEAR
GO


